Dataset:
    train_data_file_path : data/yld2000_data_input=84_output=8.h5
    input_path : input_data/d_{}
    target_path : output_data/d_{}
    test_percentage : 0.10
    val_percentage : 0.20
    
Hyperparameters:   
    num_epochs : 3
    train_batch_size : 32
    val_batch_size : 32
    test_batch_size : 32
    weight_decay : 1.0e-5
    lr : 0.0001
    stopping_delay : 400
    best_val_loss : 1.0e+10
    
Device:    
    select_GPU : 0
    
Model:
    autoencoder : True
    angle_incre1_for_stress_in_yield_locus  : 3
    angle_incre2_for_stress_in_roll_plane : 4
